#!/usr/bin/env node

/**
 * Load environment variables from .env file and generate config.js
 * This script reads .env and creates a config.js file that can be loaded in the browser
 */

const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const configPath = path.join(__dirname, 'config.js');

// Read .env file
let githubPat = null;

if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    const lines = envContent.split('\n');
    
    for (const line of lines) {
        // Skip comments and empty lines
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) {
            continue;
        }
        
        // Parse KEY=VALUE format
        const match = trimmed.match(/^GITHUB_PAT=(.+)$/);
        if (match) {
            githubPat = match[1].trim();
            // Remove quotes if present
            if ((githubPat.startsWith('"') && githubPat.endsWith('"')) ||
                (githubPat.startsWith("'") && githubPat.endsWith("'"))) {
                githubPat = githubPat.slice(1, -1);
            }
            break;
        }
    }
}

// Generate config.js
let configContent = '// Auto-generated by load-env.js - DO NOT EDIT MANUALLY\n';
configContent += '// This file is generated from .env file for local development\n';
configContent += '// In production, this file should not exist and the app will use URL parameters\n\n';

if (githubPat) {
    configContent += `window.CONFIG = {\n`;
    configContent += `    GITHUB_PAT: "${githubPat}"\n`;
    configContent += `};\n`;
} else {
    // Generate empty config if .env doesn't exist or GITHUB_PAT not found
    configContent += `window.CONFIG = {\n`;
    configContent += `    GITHUB_PAT: null\n`;
    configContent += `};\n`;
}

// Write config.js
fs.writeFileSync(configPath, configContent, 'utf8');

if (githubPat) {
    console.log('✅ config.js generated successfully from .env file');
} else {
    console.log('⚠️  .env file not found or GITHUB_PAT not set. Generated empty config.js');
    console.log('   The app will fall back to URL parameters.');
}
