#!/usr/bin/env node
// Reads data.json and emits a migration.sql that repopulates the D1 tables
// (investment_types, assets, asset_updates) from the legacy JSON store.
//
// Usage:
//   node scripts/migrate-data.mjs [--out migration.sql] [path/to/data.json]
//
// D1 executes a --file as a batch of statements, so this is idempotent:
// it deletes existing rows first, then re-inserts everything from data.json.

import { readFileSync, writeFileSync } from 'node:fs';

/** Doubles single quotes for safe embedding in a SQL string literal. */
function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

/** Renders a JS value as a SQL literal: strings quoted/escaped, booleans as 0/1, null/undefined as NULL. */
function sqlValue(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'boolean') return value ? '1' : '0';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) return 'NULL';
    return String(value);
  }
  return sqlString(value);
}

function buildInvestmentTypeInserts(metadata) {
  const types = metadata?.investment_types || [];
  return types.map(
    (t) =>
      `INSERT INTO investment_types (name, exclude_periodical_profit) VALUES (${sqlValue(
        t.name
      )}, ${sqlValue(!!t.exclude_periodical_profit)});`
  );
}

function buildAssetInsert(investment) {
  const columns = [
    'id',
    'name',
    'investment_type',
    'currency',
    'start_date',
    'initial_amount',
    'profit_type',
    'profit_rate',
    'is_active',
    'is_liquid',
    'liquidity_date',
    'track_profit',
    'staleness_reminder',
    'notes',
    'deleted_at',
  ];
  const values = [
    sqlValue(investment.id),
    sqlValue(investment.name),
    sqlValue(investment.investment_type),
    sqlValue(investment.currency),
    sqlValue(investment.start_date),
    sqlValue(investment.initial_amount),
    sqlValue(investment.profit_type),
    investment.profit_rate === undefined ? 'NULL' : sqlValue(investment.profit_rate),
    sqlValue(!!investment.is_active),
    sqlValue(!!investment.is_liquid),
    sqlValue(investment.liquidity_date ?? null),
    sqlValue(!!investment.track_profit),
    sqlValue(investment.staleness_reminder === undefined ? true : !!investment.staleness_reminder),
    sqlValue(investment.notes ?? ''),
    'NULL',
  ];
  return `INSERT INTO assets (${columns.join(', ')}) VALUES (${values.join(', ')});`;
}

function buildUpdateInserts(investment) {
  const updates = investment.updates || [];
  // Preserve original order (data.json stores updates chronologically); id is
  // auto-assigned by D1 (INTEGER PRIMARY KEY), created_by is NULL (migrated data).
  return updates
    .slice()
    .sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0))
    .map(
      (u) =>
        `INSERT INTO asset_updates (asset_id, date, amount, created_by) VALUES (${sqlValue(
          investment.id
        )}, ${sqlValue(u.date)}, ${sqlValue(u.amount)}, NULL);`
    );
}

/**
 * Pure builder: turns a parsed data.json object into the full migration SQL
 * text (string). No filesystem or process access — safe to unit test.
 */
export function buildSql(data) {
  const investments = data?.investments || [];
  const lines = [];

  lines.push('-- Generated by scripts/migrate-data.mjs. Do not edit by hand.');
  lines.push('-- Idempotent: clears existing rows before re-inserting.');
  lines.push('');
  lines.push('DELETE FROM asset_updates;');
  lines.push('DELETE FROM assets;');
  lines.push('DELETE FROM investment_types;');
  lines.push('');

  const typeInserts = buildInvestmentTypeInserts(data?.metadata);
  if (typeInserts.length > 0) {
    lines.push('-- investment_types');
    lines.push(...typeInserts);
    lines.push('');
  }

  lines.push('-- assets');
  for (const investment of investments) {
    lines.push(buildAssetInsert(investment));
  }
  lines.push('');

  lines.push('-- asset_updates');
  let updateCount = 0;
  for (const investment of investments) {
    const inserts = buildUpdateInserts(investment);
    updateCount += inserts.length;
    lines.push(...inserts);
  }

  return {
    sql: lines.join('\n') + '\n',
    counts: {
      investment_types: typeInserts.length,
      assets: investments.length,
      asset_updates: updateCount,
    },
  };
}

function main() {
  const args = process.argv.slice(2);
  let outPath = null;
  let dataPath = 'data.json';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--out') {
      outPath = args[i + 1];
      i++;
    } else {
      dataPath = args[i];
    }
  }

  const raw = readFileSync(dataPath, 'utf8');
  const data = JSON.parse(raw);
  const { sql, counts } = buildSql(data);

  if (outPath) {
    writeFileSync(outPath, sql, 'utf8');
  } else {
    process.stdout.write(sql);
  }

  process.stderr.write(
    `migrate-data: investment_types=${counts.investment_types} assets=${counts.assets} asset_updates=${counts.asset_updates}\n`
  );
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main();
}
