import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { readFileSync, writeFileSync, unlinkSync, existsSync } from 'fs';
import { join } from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);
const projectRoot = process.cwd();

/**
 * Unit tests for load-env.js script (Epic 2)
 * Tests .env file reading and config.js generation
 */

describe('load-env.js script (Epic 2)', () => {
  const envPath = join(projectRoot, '.env.test');
  const configPath = join(projectRoot, 'config.test.js');

  beforeEach(() => {
    // Clean up test files
    if (existsSync(envPath)) unlinkSync(envPath);
    if (existsSync(configPath)) unlinkSync(configPath);
  });

  afterEach(() => {
    // Clean up test files
    if (existsSync(envPath)) unlinkSync(envPath);
    if (existsSync(configPath)) unlinkSync(configPath);
  });

  it('should read GITHUB_PAT from .env file', async () => {
    // Given: .env file with GITHUB_PAT
    const testToken = 'test-github-pat-token';
    writeFileSync(envPath, `GITHUB_PAT=${testToken}\n`);

    // When: Script reads .env
    const envContent = readFileSync(envPath, 'utf8');
    const lines = envContent.split('\n');
    let githubPat = null;

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      const match = trimmed.match(/^GITHUB_PAT=(.+)$/);
      if (match) {
        githubPat = match[1].trim();
        if ((githubPat.startsWith('"') && githubPat.endsWith('"')) ||
            (githubPat.startsWith("'") && githubPat.endsWith("'"))) {
          githubPat = githubPat.slice(1, -1);
        }
        break;
      }
    }

    // Then: GITHUB_PAT should be extracted
    expect(githubPat).toBe(testToken);
  });

  it('should generate config.js with correct format', async () => {
    // Given: .env file with GITHUB_PAT
    const testToken = 'test-token-123';
    writeFileSync(envPath, `GITHUB_PAT=${testToken}\n`);

    // When: Script generates config.js
    let configContent = '// Auto-generated by load-env.js\n';
    configContent += `window.CONFIG = {\n`;
    configContent += `    GITHUB_PAT: "${testToken}"\n`;
    configContent += `};\n`;

    writeFileSync(configPath, configContent);

    // Then: config.js should have correct format
    const generated = readFileSync(configPath, 'utf8');
    expect(generated).toContain('window.CONFIG');
    expect(generated).toContain(`GITHUB_PAT: "${testToken}"`);
    expect(generated).toContain('Auto-generated');
  });

  it('should handle missing .env file gracefully', () => {
    // Given: .env file doesn't exist
    const envPath = join(projectRoot, '.env.nonexistent');
    
    // When: Script tries to read .env
    const exists = existsSync(envPath);
    
    // Then: Should handle gracefully
    expect(exists).toBe(false);
    // Script should generate empty config.js
  });

  it('should handle .env file with comments', () => {
    // Given: .env file with comments
    const envContent = `# GitHub Personal Access Token
GITHUB_PAT=test-token
# Another comment
`;
    writeFileSync(envPath, envContent);

    // When: Script reads .env
    const lines = envContent.split('\n');
    let githubPat = null;

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      const match = trimmed.match(/^GITHUB_PAT=(.+)$/);
      if (match) {
        githubPat = match[1].trim();
        break;
      }
    }

    // Then: Should extract token, ignoring comments
    expect(githubPat).toBe('test-token');
  });

  it('should handle .env file with quoted token', () => {
    // Given: .env file with quoted token
    writeFileSync(envPath, 'GITHUB_PAT="quoted-token-value"\n');

    // When: Script reads and processes .env
    const envContent = readFileSync(envPath, 'utf8');
    const lines = envContent.split('\n');
    let githubPat = null;

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      const match = trimmed.match(/^GITHUB_PAT=(.+)$/);
      if (match) {
        githubPat = match[1].trim();
        if ((githubPat.startsWith('"') && githubPat.endsWith('"')) ||
            (githubPat.startsWith("'") && githubPat.endsWith("'"))) {
          githubPat = githubPat.slice(1, -1);
        }
        break;
      }
    }

    // Then: Should remove quotes
    expect(githubPat).toBe('quoted-token-value');
  });
});
